tomcat/GET: use wget -c
Signed-off-by: geraldo netto <geraldonetto@gmail.com>
Message-Id: <1516131789-8559-50-git-send-email-geraldonetto@gmail.com>

diff --git a/tomcat/GET b/tomcat/GET
--- a/tomcat/GET
+++ b/tomcat/GET
@@ -8,7 +8,13 @@ archive=$dir.tar.gz
 
 mkdir -p upstream
 pushd upstream
-wget http://archive.apache.org/dist/tomcat/tomcat-${MAJOR}/v${VERSION}/bin/${archive}
+wget -c http://archive.apache.org/dist/tomcat/tomcat-${MAJOR}/v${VERSION}/bin/${archive}
+wget -c http://archive.apache.org/dist/tomcat/tomcat-${MAJOR}/v${VERSION}/bin/${archive}.md5
+if [ "$(md5sum -c ${archive}.md5)" != "${archive}: OK" ];
+then
+    echo "Aborting: invalid md5 for Apache Tomcat $VERSION"
+    exit 1
+fi
 tar zxvf $archive
 
 pushd $dir
